### ISSUE TITLE
Remove-mark functionality broken in v0.0.13-alpha.1 

### ISSUE THREAD

**Issue by arisgk** [automerge/automerge-prosemirror#12]
# Description

Removing a mark (bold/italics) is not working properly in `v0.0.13-alpha.1` and what is currently in the `main` branch. This recording conveys the problem when running the playground locally:

https://github.com/user-attachments/assets/47e264cf-f44e-4f23-814b-82bf922a044a

**Comment by BrianHung** [comment]
Traced it down to this change

https://github.com/automerge/automerge-prosemirror/commit/d1abb5c7025a78936d4928f51b961459e3316329#diff-1cdd5cad54822249d22829cef95393e37707fcdb58e789e1a217c9f847ff9d9aL114-R118
