### ISSUE TITLE
Unable to remove mark after deleting marked characters (cursor-only state) - v0.0.13-alpha.3

### ISSUE THREAD

**Issue by arisgk** [automerge/automerge-prosemirror#16]
# Description

When using `v0.0.13-alpha.3` I'm encountering a problem when trying to unmark text after deleting marked characters, with no text selected (i.e., in a cursor-only state).

The recording below demonstrates the issue in the playground:

https://github.com/user-attachments/assets/5a387931-e39e-4da5-9faf-76d6ebf5f83f

## How to Reproduce
1. Type some plain text
2. With the cursor at the end of the text, apply a mark (e.g. bold)
3. Type some marked characters
4. Delete all the marked characters
5. Remove the mark
6. Type some more characters

### Expected behavior

The characters typed in step 6 must be unmarked (plain text).

### Actual behavior

The characters typed in step 6 are still marked (unmarking wasn't applied properly).

**Comment by BrianHung** [comment]
Looked briefly into this; might be the same issue mentioned in #2.
